/** @type {import('sequelize-cli').Migration} */
const bcrypt = require('bcrypt');

module.exports = {
  async up(queryInterface) {
    const testUserData = [
      {
        login: 'John Lennon',
        email: 'john@gmail.com',
        password: await bcrypt.hash('john@gmail.com', 10),
        about: 'A singer, songwriter, musician and peace activist who achieved worldwide fame as the founder, co-songwriter, co-lead vocalist and rhythm guitarist of the Beatles.',
        latitude: 46.407341,
        longitude: 30.724481,
        contact: 't.me/johnLenon',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/8/85/John_Lennon_1969_%28cropped%29.jpg',
      },
      {
        login: 'Paul McCartney',
        email: 'paul@gmail.com',
        password: await bcrypt.hash('paul@gmail.com', 10),
        about: 'A singer, songwriter and musician who gained worldwide fame with the Beatles, for whom he played bass guitar and shared primary songwriting and lead vocal duties with John Lennon.',
        latitude: 46.427308,
        longitude: 30.734030,
        contact: 't.me/paulMC',
        photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3DiD-5X3OOut1P4kH9OOEIzUM9owgSIjNWw&usqp=CAU',
      },
      {
        login: 'Ringo Starr',
        email: 'starr@gmail.com',
        password: await bcrypt.hash('starr@gmail.com', 10),
        about: 'A musician, singer, songwriter and actor who achieved international fame as the drummer for the Beatles',
        latitude: 46.430584,
        longitude: 30.750565,
        contact: 't.me/starr',
        photo: 'https://happymag.tv/wp-content/uploads/2021/07/Ringo-Feat-870x524.jpg',
      },
      {
        login: 'George Harrison',
        email: 'harrison@gmail.com',
        password: await bcrypt.hash('harrison@gmail.com', 10),
        about: 'A musician and singer-songwriter who achieved international fame as the lead guitarist of the Beatles.',
        latitude: 46.428871,
        longitude: 30.761700,
        contact: 't.me/harrisonG',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/George_Harrison_1974.jpg/440px-George_Harrison_1974.jpg',
      },
      {
        login: 'Eminem',
        email: 'eminem@gmail.com',
        password: await bcrypt.hash('eminem@gmail.com', 10),
        about: 'A rapper and record producer',
        latitude: 46.436879,
        longitude: 30.750827,
        contact: 't.me/eminem',
        photo: 'https://www.biography.com/.image/t_share/MTQ3NjM5MTEzMTc5MjEwODI2/eminem_photo_by_dave_j_hogan_getty_images_entertainment_getty_187596325.jpg',
      },
      {
        login: 'XXXTentacion',
        email: 'xxxtentacion@gmail.com',
        password: await bcrypt.hash('xxxtentacion@gmail.com', 10),
        about: 'American rapper, singer, and songwriter.',
        latitude: 46.445838,
        longitude: 30.744717,
        contact: 't.me/xxxtentacion',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Xxxtentacion_%28cropped%29.jpg',
      },
      {
        login: 'Niall Horan',
        email: 'horan@gmail.com',
        password: await bcrypt.hash('horan@gmail.com', 10),
        about: 'Irish singer and songwriter',
        latitude: 46.461687,
        longitude: 30.719446,
        contact: 't.me/Niallhoran',
        photo: 'https://lastfm.freetls.fastly.net/i/u/ar0/095db5bfcde146d4aac5d270686cacf1',
      },
      {
        login: 'Liam Payne',
        email: 'payne@mail.com',
        password: await bcrypt.hash('payne@mail.com', 10),
        about: 'English singer and a member of the boy band One Direction',
        latitude: 46.468645,
        longitude: 30.702713,
        contact: 't.me/payne-com',
        photo: 'https://akamai.sscdn.co/uploadfile/letras/fotos/d/a/2/1/da2193fa7b4d151226ed0ce996377193.jpg',
      },
      {
        login: 'Harry Styles',
        email: 'styles@gmail.com',
        password: await bcrypt.hash('styles@gmail.com', 10),
        about: 'English singer, songwriter, and actor. A member of the boy band One Direction',
        latitude: 46.482038,
        longitude: 30.696194,
        contact: 't.me/harryST',
        photo: 'https://avatars.yandex.net/get-music-content/2399641/104894a9.p.631842/m1000x1000',
      },
      {
        login: 'Louis Tomlinson',
        email: 'tomlinson@gmail.com',
        password: await bcrypt.hash('tomlinson@gmail.com', 10),
        about: 'English singer and songwriter.  A member of the boy band One Direction',
        latitude: 46.491231,
        longitude: 30.722271,
        contact: 't.me/tomlinson',
        photo: 'https://i.pinimg.com/originals/91/89/5c/91895cba6aba423fb2599157824b8911.jpg',
      },
      {
        login: 'Zayn Malik',
        email: 'malil@gmail.com',
        password: await bcrypt.hash('malil@gmail.com', 10),
        about: 'British singer. Born and raised in Bradford, a member of the boy band One Direction',
        latitude: 46.480496,
        longitude: 30.736676,
        contact: 't.me/malilZ',
        photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
      },
      {
        login: 'NF',
        email: 'nf@gmail.com',
        password: await bcrypt.hash('nf@gmail.com', 10),
        about: 'American rapper, singer, songwriter and record producer.',
        latitude: 46.477640,
        longitude: 30.736916,
        contact: 't.me/nfgm',
        photo: 'https://studio21.ru/wp-content/uploads/2019/08/NF.jpg',
      },
      {
        login: 'Luke Pritchard',
        email: 'pritchard@gmail.com',
        password: await bcrypt.hash('pritchard@gmail.com', 10),
        about: 'British guitarist and singer, born 2 March 1985 in Worthing, Sussex, England, UK.',
        latitude: 46.474859,
        longitude: 30.745063,
        contact: 't.me/pritchard',
        photo: 'https://i0.wp.com/fault-magazine.com/wp-content/uploads/2018/09/Luke-Pritchard-The-Kooks-Robert-K-Baggs-Acufocal-interview-4-800x533.jpg?resize=800%2C533',
      },
      {
        login: 'Hugh Harris',
        email: 'harris@gmail.com',
        password: await bcrypt.hash('harris@gmail.com', 10),
        about: 'English musician, most known for song "Rhythm of Life',
        latitude: 46.470264,
        longitude: 30.747639,
        contact: 't.me/harrisHu',
        photo: 'https://www.irishnews.com/picturesarchive/irishnews/irishnews/2020/09/18/152031483-2f28e376-95a3-44f1-9d1d-2e14d6e24c10.jpg',
      },
      {
        login: 'Alexis Nuñez',
        email: 'alexis@gmail.com',
        password: await bcrypt.hash('alexis@gmail.com', 10),
        about: 'Drummer and percussionist from London, England, UK and member of Hejira.',
        latitude: 46.474009,
        longitude: 30.756615,
        contact: 't.me/alexisNun',
        photo: 'https://www.porteranddavies.co.uk/wp-content/uploads/2016/08/alexis-nunez.jpg',
      },
      {
        login: 'Lars Ulrich',
        email: 'ulrich@gmail.com',
        password: await bcrypt.hash('ulrich@gmail.com', 10),
        about: 'A musician best known as the drummer and co-founder of American heavy metal band Metallica.',
        latitude: 46.457738,
        longitude: 30.747987,
        contact: 't.me/ulrichLars',
        photo: 'https://lastfm.freetls.fastly.net/i/u/770x0/925d1618e55d49d68ebf1bc644af64e5.jpg',
      },
      {
        login: 'Kimberly Perry',
        email: 'perry@gmail.com',
        password: await bcrypt.hash('perry@gmail.com', 10),
        about: 'A singer and music personality associated with the band, "The Band Perry". ',
        latitude: 46.469188,
        longitude: 30.733578,
        contact: 't.me/perryKim',
        photo: 'https://www.soundslikenashville.com/wp-content/uploads/2018/03/Kimberly-Perry-The-Band-Perry-1521826749.png',
      },
    ];

    const testUsers = testUserData.map((user) => ({
      ...user,
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

    await queryInterface.bulkInsert('Users', testUsers);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Users');
  },
};
